// Code generated by Mir codegen. DO NOT EDIT.

package batchfetcherpbdsl

import (
	dsl "github.com/matejpavlovic/mir/pkg/dsl"
	events "github.com/matejpavlovic/mir/pkg/pb/batchfetcherpb/events"
	types "github.com/matejpavlovic/mir/pkg/pb/trantorpb/types"
	stdtypes "github.com/matejpavlovic/mir/stdtypes"
)

// Module-specific dsl functions for emitting events.

func NewOrderedBatch(m dsl.Module, destModule stdtypes.ModuleID, txs []*types.Transaction) {
	dsl.EmitMirEvent(m, events.NewOrderedBatch(destModule, txs))
}
