// Code generated by Mir codegen. DO NOT EDIT.

package pingpongpbdsl

import (
	dsl "github.com/matejpavlovic/mir/pkg/dsl"
	events "github.com/matejpavlovic/mir/pkg/pb/pingpongpb/events"
	stdtypes "github.com/matejpavlovic/mir/stdtypes"
)

// Module-specific dsl functions for emitting events.

func PingTime(m dsl.Module, destModule stdtypes.ModuleID) {
	dsl.EmitMirEvent(m, events.PingTime(destModule))
}
