// Code generated by Mir codegen. DO NOT EDIT.

package testerpbdsl

import (
	dsl "github.com/matejpavlovic/mir/pkg/dsl"
	types "github.com/matejpavlovic/mir/pkg/pb/eventpb/types"
	types1 "github.com/matejpavlovic/mir/pkg/pb/testerpb/types"
)

// Module-specific dsl functions for processing events.

func UponTester(m dsl.Module, handler func() error) {
	dsl.UponMirEvent[*types.Event_Tester](m, func(ev *types1.Tester) error {
		return handler()
	})
}
