// Code generated by Mir codegen. DO NOT EDIT.

package pprepvalidatorpbdsl

import (
	dsl "github.com/matejpavlovic/mir/pkg/dsl"
	events "github.com/matejpavlovic/mir/pkg/pb/ordererpb/pprepvalidatorpb/events"
	types1 "github.com/matejpavlovic/mir/pkg/pb/ordererpb/pprepvalidatorpb/types"
	types "github.com/matejpavlovic/mir/pkg/pb/pbftpb/types"
	stdtypes "github.com/matejpavlovic/mir/stdtypes"
)

// Module-specific dsl functions for emitting events.

func ValidatePreprepare[C any](m dsl.Module, destModule stdtypes.ModuleID, preprepare *types.Preprepare, context *C) {
	contextID := m.DslHandle().StoreContext(context)

	origin := &types1.ValidatePreprepareOrigin{
		Module: m.ModuleID(),
		Type:   &types1.ValidatePreprepareOrigin_Dsl{Dsl: dsl.MirOrigin(contextID)},
	}

	dsl.EmitMirEvent(m, events.ValidatePreprepare(destModule, preprepare, origin))
}

func PreprepareValidated(m dsl.Module, destModule stdtypes.ModuleID, error error, origin *types1.ValidatePreprepareOrigin) {
	dsl.EmitMirEvent(m, events.PreprepareValidated(destModule, error, origin))
}
