// Code generated by Mir codegen. DO NOT EDIT.

package ordererpbdsl

import (
	dsl "github.com/matejpavlovic/mir/pkg/dsl"
	dsl1 "github.com/matejpavlovic/mir/pkg/pb/messagepb/dsl"
	types1 "github.com/matejpavlovic/mir/pkg/pb/messagepb/types"
	types "github.com/matejpavlovic/mir/pkg/pb/ordererpb/types"
	stdtypes "github.com/matejpavlovic/mir/stdtypes"
)

// Module-specific dsl functions for processing net messages.

func UponMessageReceived[W types.Message_TypeWrapper[M], M any](m dsl.Module, handler func(from stdtypes.NodeID, msg *M) error) {
	dsl1.UponMessageReceived[*types1.Message_Orderer](m, func(from stdtypes.NodeID, msg *types.Message) error {
		w, ok := msg.Type.(W)
		if !ok {
			return nil
		}

		return handler(from, w.Unwrap())
	})
}
