// Code generated by Mir codegen. DO NOT EDIT.

package batchfetcherpbevents

import (
	types2 "github.com/matejpavlovic/mir/pkg/pb/batchfetcherpb/types"
	types1 "github.com/matejpavlovic/mir/pkg/pb/eventpb/types"
	types "github.com/matejpavlovic/mir/pkg/pb/trantorpb/types"
	stdtypes "github.com/matejpavlovic/mir/stdtypes"
)

func NewOrderedBatch(destModule stdtypes.ModuleID, txs []*types.Transaction) *types1.Event {
	return &types1.Event{
		DestModule: destModule,
		Type: &types1.Event_BatchFetcher{
			BatchFetcher: &types2.Event{
				Type: &types2.Event_NewOrderedBatch{
					NewOrderedBatch: &types2.NewOrderedBatch{
						Txs: txs,
					},
				},
			},
		},
	}
}
